"""
Django settings for jobtracker_server project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads .env (see .env.example) if present — a plain os.environ.get() below
# still works fine without this (e.g. env vars exported directly, common in
# CI), load_dotenv() just additionally reads a local .env file into the
# process environment if one exists. Never overwrites a var already set in
# the real environment (override=False is the default), so an explicit
# `export SECRET_KEY=...` always wins over whatever .env says.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Sourced
# from the environment (see .env.example) rather than hardcoded — this used
# to be the plain 'django-insecure-...' value django-admin startproject
# scaffolds by default, which is fine for a throwaway local key but not
# something that belongs committed to a repo, professional or not. The
# fallback below is still an "insecure" placeholder, same spirit as
# Django's own scaffolded default — it just means "you forgot to set one,"
# not "safe to use as-is."
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-set-a-real-secret-key-in-your-.env-file')

# SECURITY WARNING: don't run with debug turned on in production! Defaults
# to True for local dev (this server only ever runs locally alongside the
# extension — see ALLOWED_HOSTS below), override via .env if that ever
# changes.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# This server only ever runs locally alongside the extension — never deployed.
# Overridable via .env (comma-separated) in case that assumption ever changes.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Ollama connection — override via env vars to point at a different instance/model
# without touching code. See .env.example.
OLLAMA_URL = os.environ.get('OLLAMA_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.1:8b')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analysis',
    'assistant',
    'accounts',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT (Django admin's CSS/JS) directly — only relevant
    # inside the Docker image, where there's no separate nginx/CDN in front
    # of gunicorn. A no-op for local dev (manage.py runserver already serves
    # static files itself when DEBUG=True), so this is safe to leave in
    # unconditionally rather than branching on how the app happens to be run.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobtracker_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobtracker_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# The real source of truth for tracked applications/profile data (accounts/
# tracker apps) — chrome.storage.local no longer holds this; it now only
# holds the session's auth token. SQLite rather than a separate DB service:
# this server only ever runs locally alongside the extension, one file is
# enough, and it avoids needing a database server installed/running/
# credentialed just for a single-machine personal tool.

# DATABASE_PATH lets the Docker setup point this at a named-volume-mounted
# path (see docker-compose.yml) so the database survives a container
# rebuild — local/non-container dev doesn't set this and keeps using the
# same BASE_DIR/db.sqlite3 it always has.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DATABASE_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Only populated by `collectstatic`, which the Dockerfile runs at build
# time — irrelevant to local/non-container dev (manage.py runserver doesn't
# need STATIC_ROOT at all).
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
